### ISSUE TITLE
Pulling jessie-20180926 (current latest) fails on rpi1

### ISSUE THREAD

**Issue by StefanSchoof** [resin-io-library/resin-rpi-raspbian#82]
I have a strange problem. Pulling the current latest (jessie-20180926) fails on my rpi1:

```
$ docker pull resin/rpi-raspbian:jessie-20180926
error pulling image configuration: Get https://production.cloudflare.docker.com/registry-v2/docker/registry/v2/blobs/sha256/ab/abe564b9f580b5631c14d54358babedbffde08207218756c5ee191f5daebc256/data?verify=1538821028-X9vHOQq%2BBhwHRG%2FkeZ5EGy1vur4%3D: net/http: TLS handshake timeout
```
The Sha256 hash is sometimes different, but I think there was only three or four different.

Pulling the previous jessie-20180815 works. Also pulling this image on a amd64 PC works. First I thought this is a temporary problem in the docker hub infrastructure, but I tested daily since the 20180929 and it had failed every day.

Any Ideas how I can fix this?

**Comment by imrehg** [comment]
Hi, @StefanSchoof, what version of Docker are you have on the Pi1? (what OS are you running on the Pi1?)

We know issues with Docker HUB regarding pulling on Pi1 (well, armv6) devices, since they switched to Cloudflare, but we don't have enough info to pin it down.

The newer Docker/Balena versions should be working, but there's a window of versions that we've seen the same issue you report (though reproducibly). Thus hearing more details from you could helps us hunt down the issue further!

Have a potential workaround, but it depends on the OS/Docker that you are using, so that would help a lot to know.

**Comment by StefanSchoof** [comment]
Thanks for the reply:
It is an raspian stretch with the kernel from Hypriot (4.14.34-hypriotos+ #2 Sun Apr 22 15:29:32 UTC 2018 armv6l GNU/Linux)  and docker from `deb [arch=armhf] https://download.docker.com/linux/raspbian stretch stable`
```
$ docker --version
Docker version 18.06.1-ce, build e68fc7a
```

**Comment by StefanSchoof** [comment]
I found a solution for me.

I added

```
  "max-concurrent-downloads": 1
```

to my `/etc/docker/daemon.json`. Now the pull works. I assume the rpi1 has not enough power for three parallel downloads. Why some images were working and others not is still mysterious, but now all are working.
